export const marketplaceData = [
    {
      id: 1,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 2,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 3,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 4,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 5,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 6,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 7,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 8,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 9,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    {
      id: 10,
      image: require("@/assets/images/adaptive-icon.png"),
      title: "JOHN PORK",
      price: 9999,
      size: "XXS",
      time: "2 MIN AGO",
      boosted: true,
    },
    // Add more items as needed
  ];